// This file was auto-generated by the ssg init command.

import groovy.transform.BaseScript
import com.jessebrault.ssg.buildscript.BuildScriptBase

@BaseScript
BuildScriptBase b

abstractBuild(name: 'mySiteAll', extending: 'default') {
    siteSpec {
        name = 'My Site'
        baseUrl = 'https://mysite.com'
    }
}

build(name: 'production', extending: 'mySiteAll') { }

build(name: 'preview', extending: 'mySiteAll') {
    siteSpec { base ->
        baseUrl = base.baseUrl + '/preview' // https://mysite.com/preview
    }
}
