// This file was auto-generated by the ssg init command.

build {
    name = 'My Simple Build'
    outDir = new File('mySimpleBuild')

    config {
        // Config options here
    }

    globals {
        siteTitle = 'My Simple Site'
    }
}