name: StaticSiteGenerator Release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          cache: gradle
      - name: Gradle Test
        run: ./gradlew test
      - name: Gradle Install
        run: ./gradlew :cli:assembleDist
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'cli/build/distributions/*.tar,cli/build/distributions/*.zip'
          name: ${{ env.GITHUB_REF_NAME }}
          tag: ${{ env.GITHUB_REF_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          
